// lib/repositories/DomainRepository.js
// Repository for domain-related database operations

import { BaseRepository } from './BaseRepository';
import { query, withTransaction } from '../pg';
import crypto from 'crypto';

/**
 * Transform database row to domain object
 * @param {Object} row
 * @returns {Object}
 */
function transformDomain(row) {
  return {
    id: row.id,
    displayId: row.display_id,
    name: row.name,
    notes: row.notes,
    owner: row.owner,
    sharedWith: row.shared_with || [],
  };
}

/**
 * Repository for Domain operations
 */
export class DomainRepository extends BaseRepository {
  constructor() {
    super('domains', 'id');
  }

  /**
   * Find all domains accessible to a user
   * @param {string} userId
   * @param {string} userRole
   * @returns {Promise<Object[]>}
   */
  async findAccessibleByUser(userId, userRole) {
    let result;

    if (userRole === 'admin') {
      // Admin sees all domains
      result = await query(
        `SELECT d.*,
          COALESCE(array_agg(dm.user_id) FILTER (WHERE dm.user_id IS NOT NULL), '{}') AS shared_with
        FROM domains d
        LEFT JOIN domain_members dm ON dm.domain_id = d.id
        GROUP BY d.id
        ORDER BY d.created_at DESC`,
        []
      );
    } else {
      // Non-admins see owned or shared domains
      result = await query(
        `SELECT d.*,
          COALESCE(array_agg(dm2.user_id) FILTER (WHERE dm2.user_id IS NOT NULL), '{}') AS shared_with
        FROM domains d
        LEFT JOIN domain_members dm ON dm.domain_id = d.id
        LEFT JOIN domain_members dm2 ON dm2.domain_id = d.id
        WHERE d.owner = $1 OR dm.user_id = $1
        GROUP BY d.id
        ORDER BY d.created_at DESC`,
        [userId]
      );
    }

    return result.rows.map(transformDomain);
  }

  /**
   * Find a domain by display ID (e.g., DOM-0001)
   * @param {string} displayId
   * @returns {Promise<Object|null>}
   */
  async findByDisplayId(displayId) {
    const result = await query(
      `SELECT d.*,
        COALESCE(array_agg(dm.user_id) FILTER (WHERE dm.user_id IS NOT NULL), '{}') AS shared_with
      FROM domains d
      LEFT JOIN domain_members dm ON dm.domain_id = d.id
      WHERE d.display_id = $1
      GROUP BY d.id`,
      [displayId]
    );

    if (result.rows.length === 0) {
      return null;
    }

    return transformDomain(result.rows[0]);
  }

  /**
   * Find a domain by ID
   * @param {string} domainId
   * @returns {Promise<Object|null>}
   */
  async findByIdWithMembers(domainId) {
    const result = await query(
      `SELECT d.*,
        COALESCE(array_agg(dm.user_id) FILTER (WHERE dm.user_id IS NOT NULL), '{}') AS shared_with
      FROM domains d
      LEFT JOIN domain_members dm ON dm.domain_id = d.id
      WHERE d.id = $1
      GROUP BY d.id`,
      [domainId]
    );

    if (result.rows.length === 0) {
      return null;
    }

    return transformDomain(result.rows[0]);
  }

  /**
   * Create a new domain with owner as member
   * @param {Object} data
   * @param {string} data.name
   * @param {string} [data.notes]
   * @param {string} ownerId
   * @returns {Promise<Object>}
   */
  async createDomain(data, ownerId) {
    const { name, notes } = data;

    if (!name) {
      throw new Error('name is required');
    }

    const id = crypto.randomUUID();
    // Generate slug from name (lowercase, replace spaces with hyphens, remove special chars)
    const baseSlug = name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    // Add short random suffix to ensure uniqueness
    const slug = `${baseSlug}-${crypto.randomUUID().slice(0, 8)}`;

    return withTransaction(async (client) => {
      // Create domain - display_id is auto-generated by trigger
      const result = await client.query(
        `INSERT INTO domains (id, name, slug, notes, owner) VALUES ($1, $2, $3, $4, $5) RETURNING display_id`,
        [id, name, slug, notes || '', ownerId]
      );

      // Add owner as member
      await client.query(
        `INSERT INTO domain_members (domain_id, user_id, role) VALUES ($1, $2, 'owner') ON CONFLICT DO NOTHING`,
        [id, ownerId]
      );

      return {
        id,
        displayId: result.rows[0]?.display_id,
        name,
        notes: notes || '',
        owner: ownerId,
        sharedWith: [],
      };
    });
  }

  /**
   * Check if user is owner of domain
   * @param {string} domainId
   * @param {string} userId
   * @param {string} userRole
   * @returns {Promise<{isOwner: boolean, domain: Object|null}>}
   */
  async checkOwnership(domainId, userId, userRole) {
    const result = await query(
      `SELECT * FROM domains WHERE id = $1`,
      [domainId]
    );

    if (result.rows.length === 0) {
      return { isOwner: false, domain: null };
    }

    const domain = result.rows[0];
    const isOwner = domain.owner === userId || userRole === 'admin';

    return { isOwner, domain };
  }

  /**
   * Share domain with a user
   * @param {string} domainId
   * @param {string} targetUserId
   * @param {string} [targetRole='viewer']
   * @returns {Promise<void>}
   */
  async shareDomain(domainId, targetUserId, targetRole = 'viewer') {
    await query(
      `INSERT INTO domain_members (domain_id, user_id, role)
       VALUES ($1, $2, $3)
       ON CONFLICT (domain_id, user_id) DO UPDATE SET role = EXCLUDED.role`,
      [domainId, targetUserId, targetRole]
    );
  }

  /**
   * Remove share from domain
   * @param {string} domainId
   * @param {string} targetUserId
   * @returns {Promise<void>}
   */
  async unshareDomain(domainId, targetUserId) {
    await query(
      `DELETE FROM domain_members WHERE domain_id = $1 AND user_id = $2`,
      [domainId, targetUserId]
    );
  }

  /**
   * Update domain details
   * @param {string} domainId
   * @param {Object} data
   * @param {string} [data.name]
   * @param {string} [data.notes]
   * @returns {Promise<Object|null>}
   */
  async updateDomain(domainId, data) {
    const { name, notes } = data;

    const result = await query(
      `UPDATE domains SET
        name = COALESCE($1, name),
        notes = COALESCE($2, notes)
      WHERE id = $3
      RETURNING *`,
      [name, notes, domainId]
    );

    if (result.rows.length === 0) {
      return null;
    }

    return this.findByIdWithMembers(domainId);
  }

  /**
   * Delete a domain
   * @param {string} domainId
   * @returns {Promise<boolean>}
   */
  async deleteDomain(domainId) {
    const result = await query(
      `DELETE FROM domains WHERE id = $1 RETURNING id`,
      [domainId]
    );
    return result.rowCount > 0;
  }

  /**
   * Get domain members
   * @param {string} domainId
   * @returns {Promise<Object[]>}
   */
  async getMembers(domainId) {
    const result = await query(
      `SELECT dm.*, u.username
       FROM domain_members dm
       JOIN users u ON u.id = dm.user_id
       WHERE dm.domain_id = $1`,
      [domainId]
    );
    return result.rows;
  }
}

// Export singleton instance
export const domainRepository = new DomainRepository();

export default domainRepository;
